### ISSUE TITLE
Old host files

### ISSUE THREAD

**Issue by AnotherPillow** [filecoffee/filehost#2]
Did I miss any notice, or was it shut down without warning? Are the files gone forever currently, or is it still possible to retrieve one's uploads?

**Comment by abcdan** [comment]
Hey @AnotherPillow. If you are in the Discord, could you please open a ticket?

**Comment by AnotherPillow** [comment]
> Hey @AnotherPillow. If you are in the Discord, could you please open a ticket?

Done.
